[phases.setup]
nixPkgs = ['python311', 'postgresql', 'gcc']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.build]
cmds = ['python -m alembic upgrade head']

[start]
cmd = 'python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT'
