[phases.setup]
nixPkgs = ['python311', 'postgresql', 'gcc']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['alembic upgrade head']

[start]
cmd = 'uvicorn backend.main:app --host 0.0.0.0 --port $PORT'
